### ISSUE TITLE
Cheat védelem frissítése 1.16.x

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3644]
**Szerver**: összes

Az alábbi hibák jöttek elő eddig:
- [x] Álomfutó (strider) felülés hiba #3638 (javítva)
- [x] Lélekfutás enchant lélekhomokon hiba #3641 
- [x] Osonás eventen beakadnak a játékosok, és nem lehet továbbmenni. FLY (17191VL)-t ír pl
- [x] 1.16-os lépcsőkön nem lehet átmenni #3701 
- [ ] Slime blokk trambulin #3699 (jelentve a fejlesztőnek)

**Comment by andris155** [comment]
Egy kis idő biztosan lesz még ezeket megcsinálják. Alapszinten már támogatja az 1.16.1-et.

**Comment by andris155** [comment]
A strider támogatás holnap bekerül. A többit majd tesztelni kell, hogy még mindig problémás-e.

**Comment by andris155** [comment]
Az osonás eventen még mindig beakadnak a játékosok?

**Comment by andris155** [comment]
Végig vittem az eventet játékos jogokkal. Nem volt vele semmiféle gond. Szerintem javították a hibát már.

**Comment by andris155** [comment]
A Slime blokkos hibát javítják majd a következő frissítésben ha lehetséges megoldani. Az 1.16.1-el kapcsolatban viszont én nem tudok már ismert hibáról.
